baseURL = 'https://usysrc.dev/'
languageCode = 'en-us'
title = 'usysrc.dev'
theme = 'usysrcTheme'
assetDir = "static"

[menu]
  [[menu.main]]
    name = "code"
    url = "/pages/code/"
    weight = 1
  [[menu.main]]
    name = "music"
    url = "/pages/music/"
    weight = 2
  [[menu.main]]
    name = "games"
    url = "/pages/games/"
    weight = 3 

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4
