name: build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: get latest
    - uses: actions/checkout@v2
    - name: sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}