name: Deploy to Production
on:
  push:
    branches: [main]
jobs:
  prod-deploy:
    name: prod-deploy
    runs-on: ubuntu-latest
    steps:
      - name: get latest
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.139.5"
      - name: Build
        run: hugo --minify
      - name: sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          local-dir: "public/"
